source 'https://rubygems.org'

gem 'sinatra'
gem 'rerun'
gem 'rb-fsevent'
gem 'nokogiri'
gem 'sinatra-partial'
gem 'sinatra-json'
gem 'coderay', :require =>  'coderay'
gem 'erubis'
gem 'resque'
gem 'rake'
gem 'fog'